// Generated register defines for keccak_sponge

#ifndef _KECCAK_SPONGE_REG_DEFS_
#define _KECCAK_SPONGE_REG_DEFS_

#ifdef __cplusplus
extern "C" {
#endif
// Register width
#define KECCAK_SPONGE_PARAM_REG_WIDTH 32

// Source base address in system memory for DMA reads
#define KECCAK_SPONGE_SRC_ADDR_REG_OFFSET 0x0

// Destination base address in system memory for DMA writes
#define KECCAK_SPONGE_DST_ADDR_REG_OFFSET 0x4

// Sponge input length in bytes
#define KECCAK_SPONGE_DATA_LEN_REG_OFFSET 0x8

// Sponge mode output length in bytes
#define KECCAK_SPONGE_OUT_LEN_REG_OFFSET 0xc

// Sponge mode domain/suffix byte
#define KECCAK_SPONGE_DOMAIN_REG_OFFSET 0x10
#define KECCAK_SPONGE_DOMAIN_DOMAIN_MASK 0xff
#define KECCAK_SPONGE_DOMAIN_DOMAIN_OFFSET 0
#define KECCAK_SPONGE_DOMAIN_DOMAIN_FIELD \
  ((bitfield_field32_t) { .mask = KECCAK_SPONGE_DOMAIN_DOMAIN_MASK, .index = KECCAK_SPONGE_DOMAIN_DOMAIN_OFFSET })

// Control register for DMA Keccak transaction
#define KECCAK_SPONGE_CTRL_REG_OFFSET 0x14
#define KECCAK_SPONGE_CTRL_START_BIT 0

// Status register for DMA Keccak transaction
#define KECCAK_SPONGE_STATUS_REG_OFFSET 0x18
#define KECCAK_SPONGE_STATUS_DONE_BIT 0
#define KECCAK_SPONGE_STATUS_BUSY_BIT 1
#define KECCAK_SPONGE_STATUS_ERROR_BIT 2

// Cycles from accepted start to transaction completion or error
#define KECCAK_SPONGE_LAST_OP_CYCLES_REG_OFFSET 0x1c

// Accumulated Keccak core active cycles in the last transaction
#define KECCAK_SPONGE_LAST_CORE_CYCLES_REG_OFFSET 0x20

// Number of completed or errored hardware transactions
#define KECCAK_SPONGE_OP_COUNT_REG_OFFSET 0x24

// Number of Keccak core permutations in the last transaction
#define KECCAK_SPONGE_LAST_CORE_PERMS_REG_OFFSET 0x28

// Compatibility aliases used by the Keccak sponge DMA driver.
#define KECCAK_SPONGE_DMA_PARAM_REG_WIDTH KECCAK_SPONGE_PARAM_REG_WIDTH
#define KECCAK_SPONGE_DMA_WORD_BYTES 4u
#define KECCAK_SPONGE_DMA_SRC_ADDR_REG_OFFSET KECCAK_SPONGE_SRC_ADDR_REG_OFFSET
#define KECCAK_SPONGE_DMA_DST_ADDR_REG_OFFSET KECCAK_SPONGE_DST_ADDR_REG_OFFSET
#define KECCAK_SPONGE_DMA_DATA_LEN_REG_OFFSET KECCAK_SPONGE_DATA_LEN_REG_OFFSET
#define KECCAK_SPONGE_DMA_OUT_LEN_REG_OFFSET KECCAK_SPONGE_OUT_LEN_REG_OFFSET
#define KECCAK_SPONGE_DMA_DOMAIN_REG_OFFSET KECCAK_SPONGE_DOMAIN_REG_OFFSET
#define KECCAK_SPONGE_DMA_CTRL_REG_OFFSET KECCAK_SPONGE_CTRL_REG_OFFSET
#define KECCAK_SPONGE_DMA_CTRL_START_BIT KECCAK_SPONGE_CTRL_START_BIT
#define KECCAK_SPONGE_DMA_STATUS_REG_OFFSET KECCAK_SPONGE_STATUS_REG_OFFSET
#define KECCAK_SPONGE_DMA_STATUS_DONE_BIT KECCAK_SPONGE_STATUS_DONE_BIT
#define KECCAK_SPONGE_DMA_STATUS_BUSY_BIT KECCAK_SPONGE_STATUS_BUSY_BIT
#define KECCAK_SPONGE_DMA_STATUS_ERROR_BIT KECCAK_SPONGE_STATUS_ERROR_BIT
#define KECCAK_SPONGE_DMA_LAST_OP_CYCLES_REG_OFFSET KECCAK_SPONGE_LAST_OP_CYCLES_REG_OFFSET
#define KECCAK_SPONGE_DMA_LAST_CORE_CYCLES_REG_OFFSET KECCAK_SPONGE_LAST_CORE_CYCLES_REG_OFFSET
#define KECCAK_SPONGE_DMA_OP_COUNT_REG_OFFSET KECCAK_SPONGE_OP_COUNT_REG_OFFSET
#define KECCAK_SPONGE_DMA_LAST_CORE_PERMS_REG_OFFSET KECCAK_SPONGE_LAST_CORE_PERMS_REG_OFFSET

#ifdef __cplusplus
}  // extern "C"
#endif
#endif  // _KECCAK_SPONGE_REG_DEFS_
// End generated register defines for keccak_sponge
